//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerMap"",
            ""id"": ""034a306c-9995-4702-ba35-194538266ca2"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""25746da8-129a-4e3b-97e9-d34bf435d7d5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""210e6cfe-261e-4e9c-b326-6c75ec7f0f4f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f2a3a1d3-8fab-4488-805b-4f56e4e10d56"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""75a2da4b-eaf0-43ac-9a04-17ae16c6e8dd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b40b0792-b515-41ec-bdf2-73b5f97b0327"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""970118d7-1636-4e94-b93c-09fe0ed293fb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7ae3c9f7-c77e-4587-82aa-367ecfc936f7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5d714f7c-d73e-46f8-9003-c61a4d893965"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InventoryMap"",
            ""id"": ""a3b1922f-5963-47f4-8882-bafac1824f51"",
            ""actions"": [
                {
                    ""name"": ""Choose first cell"",
                    ""type"": ""Button"",
                    ""id"": ""38abc9b6-fd9e-464d-8353-d380ac2aa0c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Choose second cell"",
                    ""type"": ""Button"",
                    ""id"": ""0c9037d8-7a3a-41c3-92fd-185e6770df86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Choose third cell"",
                    ""type"": ""Button"",
                    ""id"": ""1e151e78-0916-424f-b807-02d42c081bcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Choose fourth cell"",
                    ""type"": ""Button"",
                    ""id"": ""8611d126-3241-4df4-bea6-1f358cf1bff0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Open/Close back pack"",
                    ""type"": ""Button"",
                    ""id"": ""c7f3c3b0-61ba-4370-9cf4-7fd504418835"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a2f9a90b-a73b-451e-909a-443ffd13c2b4"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Choose first cell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ea69903-1ef0-404d-afeb-2b49a3c71d37"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Choose second cell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c283153-6845-4357-adcb-315cc314c87c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Choose third cell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4650cca3-0a10-4d3e-a855-890e164de949"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Choose fourth cell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""757d0e66-fe8c-49f2-9796-92c5b12494c3"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open/Close back pack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuActions"",
            ""id"": ""119f7e97-4665-4427-bf7f-668e7be427c0"",
            ""actions"": [
                {
                    ""name"": ""Open/Close game menu"",
                    ""type"": ""Button"",
                    ""id"": ""29ce6929-1f59-4865-85d9-bdf2a1f80d9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8e7c3c6e-f5d7-42bd-acea-c18543eb093a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open/Close game menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PSScheme"",
            ""bindingGroup"": ""PSScheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerMap
        m_PlayerMap = asset.FindActionMap("PlayerMap", throwIfNotFound: true);
        m_PlayerMap_Movement = m_PlayerMap.FindAction("Movement", throwIfNotFound: true);
        m_PlayerMap_Interact = m_PlayerMap.FindAction("Interact", throwIfNotFound: true);
        // InventoryMap
        m_InventoryMap = asset.FindActionMap("InventoryMap", throwIfNotFound: true);
        m_InventoryMap_Choosefirstcell = m_InventoryMap.FindAction("Choose first cell", throwIfNotFound: true);
        m_InventoryMap_Choosesecondcell = m_InventoryMap.FindAction("Choose second cell", throwIfNotFound: true);
        m_InventoryMap_Choosethirdcell = m_InventoryMap.FindAction("Choose third cell", throwIfNotFound: true);
        m_InventoryMap_Choosefourthcell = m_InventoryMap.FindAction("Choose fourth cell", throwIfNotFound: true);
        m_InventoryMap_OpenClosebackpack = m_InventoryMap.FindAction("Open/Close back pack", throwIfNotFound: true);
        // MenuActions
        m_MenuActions = asset.FindActionMap("MenuActions", throwIfNotFound: true);
        m_MenuActions_OpenClosegamemenu = m_MenuActions.FindAction("Open/Close game menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMap
    private readonly InputActionMap m_PlayerMap;
    private List<IPlayerMapActions> m_PlayerMapActionsCallbackInterfaces = new List<IPlayerMapActions>();
    private readonly InputAction m_PlayerMap_Movement;
    private readonly InputAction m_PlayerMap_Interact;
    public struct PlayerMapActions
    {
        private @InputActions m_Wrapper;
        public PlayerMapActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerMap_Movement;
        public InputAction @Interact => m_Wrapper.m_PlayerMap_Interact;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMapActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMapActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMapActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IPlayerMapActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IPlayerMapActions instance)
        {
            if (m_Wrapper.m_PlayerMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMapActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMapActions @PlayerMap => new PlayerMapActions(this);

    // InventoryMap
    private readonly InputActionMap m_InventoryMap;
    private List<IInventoryMapActions> m_InventoryMapActionsCallbackInterfaces = new List<IInventoryMapActions>();
    private readonly InputAction m_InventoryMap_Choosefirstcell;
    private readonly InputAction m_InventoryMap_Choosesecondcell;
    private readonly InputAction m_InventoryMap_Choosethirdcell;
    private readonly InputAction m_InventoryMap_Choosefourthcell;
    private readonly InputAction m_InventoryMap_OpenClosebackpack;
    public struct InventoryMapActions
    {
        private @InputActions m_Wrapper;
        public InventoryMapActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Choosefirstcell => m_Wrapper.m_InventoryMap_Choosefirstcell;
        public InputAction @Choosesecondcell => m_Wrapper.m_InventoryMap_Choosesecondcell;
        public InputAction @Choosethirdcell => m_Wrapper.m_InventoryMap_Choosethirdcell;
        public InputAction @Choosefourthcell => m_Wrapper.m_InventoryMap_Choosefourthcell;
        public InputAction @OpenClosebackpack => m_Wrapper.m_InventoryMap_OpenClosebackpack;
        public InputActionMap Get() { return m_Wrapper.m_InventoryMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InventoryMapActions set) { return set.Get(); }
        public void AddCallbacks(IInventoryMapActions instance)
        {
            if (instance == null || m_Wrapper.m_InventoryMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InventoryMapActionsCallbackInterfaces.Add(instance);
            @Choosefirstcell.started += instance.OnChoosefirstcell;
            @Choosefirstcell.performed += instance.OnChoosefirstcell;
            @Choosefirstcell.canceled += instance.OnChoosefirstcell;
            @Choosesecondcell.started += instance.OnChoosesecondcell;
            @Choosesecondcell.performed += instance.OnChoosesecondcell;
            @Choosesecondcell.canceled += instance.OnChoosesecondcell;
            @Choosethirdcell.started += instance.OnChoosethirdcell;
            @Choosethirdcell.performed += instance.OnChoosethirdcell;
            @Choosethirdcell.canceled += instance.OnChoosethirdcell;
            @Choosefourthcell.started += instance.OnChoosefourthcell;
            @Choosefourthcell.performed += instance.OnChoosefourthcell;
            @Choosefourthcell.canceled += instance.OnChoosefourthcell;
            @OpenClosebackpack.started += instance.OnOpenClosebackpack;
            @OpenClosebackpack.performed += instance.OnOpenClosebackpack;
            @OpenClosebackpack.canceled += instance.OnOpenClosebackpack;
        }

        private void UnregisterCallbacks(IInventoryMapActions instance)
        {
            @Choosefirstcell.started -= instance.OnChoosefirstcell;
            @Choosefirstcell.performed -= instance.OnChoosefirstcell;
            @Choosefirstcell.canceled -= instance.OnChoosefirstcell;
            @Choosesecondcell.started -= instance.OnChoosesecondcell;
            @Choosesecondcell.performed -= instance.OnChoosesecondcell;
            @Choosesecondcell.canceled -= instance.OnChoosesecondcell;
            @Choosethirdcell.started -= instance.OnChoosethirdcell;
            @Choosethirdcell.performed -= instance.OnChoosethirdcell;
            @Choosethirdcell.canceled -= instance.OnChoosethirdcell;
            @Choosefourthcell.started -= instance.OnChoosefourthcell;
            @Choosefourthcell.performed -= instance.OnChoosefourthcell;
            @Choosefourthcell.canceled -= instance.OnChoosefourthcell;
            @OpenClosebackpack.started -= instance.OnOpenClosebackpack;
            @OpenClosebackpack.performed -= instance.OnOpenClosebackpack;
            @OpenClosebackpack.canceled -= instance.OnOpenClosebackpack;
        }

        public void RemoveCallbacks(IInventoryMapActions instance)
        {
            if (m_Wrapper.m_InventoryMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInventoryMapActions instance)
        {
            foreach (var item in m_Wrapper.m_InventoryMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InventoryMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InventoryMapActions @InventoryMap => new InventoryMapActions(this);

    // MenuActions
    private readonly InputActionMap m_MenuActions;
    private List<IMenuActionsActions> m_MenuActionsActionsCallbackInterfaces = new List<IMenuActionsActions>();
    private readonly InputAction m_MenuActions_OpenClosegamemenu;
    public struct MenuActionsActions
    {
        private @InputActions m_Wrapper;
        public MenuActionsActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenClosegamemenu => m_Wrapper.m_MenuActions_OpenClosegamemenu;
        public InputActionMap Get() { return m_Wrapper.m_MenuActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActionsActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsActionsCallbackInterfaces.Add(instance);
            @OpenClosegamemenu.started += instance.OnOpenClosegamemenu;
            @OpenClosegamemenu.performed += instance.OnOpenClosegamemenu;
            @OpenClosegamemenu.canceled += instance.OnOpenClosegamemenu;
        }

        private void UnregisterCallbacks(IMenuActionsActions instance)
        {
            @OpenClosegamemenu.started -= instance.OnOpenClosegamemenu;
            @OpenClosegamemenu.performed -= instance.OnOpenClosegamemenu;
            @OpenClosegamemenu.canceled -= instance.OnOpenClosegamemenu;
        }

        public void RemoveCallbacks(IMenuActionsActions instance)
        {
            if (m_Wrapper.m_MenuActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActionsActions @MenuActions => new MenuActionsActions(this);
    private int m_PSSchemeSchemeIndex = -1;
    public InputControlScheme PSSchemeScheme
    {
        get
        {
            if (m_PSSchemeSchemeIndex == -1) m_PSSchemeSchemeIndex = asset.FindControlSchemeIndex("PSScheme");
            return asset.controlSchemes[m_PSSchemeSchemeIndex];
        }
    }
    public interface IPlayerMapActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IInventoryMapActions
    {
        void OnChoosefirstcell(InputAction.CallbackContext context);
        void OnChoosesecondcell(InputAction.CallbackContext context);
        void OnChoosethirdcell(InputAction.CallbackContext context);
        void OnChoosefourthcell(InputAction.CallbackContext context);
        void OnOpenClosebackpack(InputAction.CallbackContext context);
    }
    public interface IMenuActionsActions
    {
        void OnOpenClosegamemenu(InputAction.CallbackContext context);
    }
}
